{% set name = "PyQt" %}
{% set version = "5.15.4" %}

{% set sip_name = "PyQt5-sip" %}
{% set sip_version = "12.9.0" %}

package:
  name: pyqt-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}{{ version[0] }}/{{ name }}{{ version[0] }}-{{ version }}.tar.gz
    sha256: 2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be
    folder: pyqt

  - url:  https://pypi.io/packages/source/{{ sip_name[0] }}/{{ sip_name }}/{{ sip_name.replace('-', '_') }}-{{ sip_version }}.tar.gz
    sha256: d3e4489d7c2b0ece9d203ae66e573939f7f60d4d29e089c9f11daa17cfeaae32
    folder: pyqt_sip

build:
  number: 0

outputs:
  - name: {{ sip_name|lower }}
    version: {{ sip_version }}
    script: pyqt_sip_build.sh   # [not win]
    script: pyqt_sip_bld.bat    # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
        - sip
        - packaging
        - toml
    test:
      imports:
        - PyQt5.sip

  - name: pyqt-impl
    version: {{ version }}
    script: pyqt_build.sh  # [not win]
    script: pyqt_bld.bat  # [win]
    requirements:
      run_constrained:                                            # [osx and x86_64]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-libgl') }}  # [linux]
        - {{ cdt('mesa-libegl') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - {{ cdt('alsa-lib-devel') }}    # [linux]
        - {{ cdt('cups-devel') }}    # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('alsa-lib-devel') }}        # [linux]
        - {{ cdt('gtk2-devel') }}            # [linux]
        - {{ cdt('gtkmm24-devel') }}         # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('pciutils-devel') }}        # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('cups-devel') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('expat-devel') }}           # [linux]
        - {{ cdt('pcre') }}                  # [linux]
        - jom                                # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - sip
        - toml
        - pyqt-builder
        - packaging
        - qt-main
      run:
        - python
        - qt-main
        - pyqt5-sip
      test:
        imports:
          - PyQt5
          # - simplejson.tests
        requires:
          - pip
        commands:
          - pip check

  - name: {{ name|lower }}
    build:
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    requirements:
      run_constrained:                                            # [osx and x86_64]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pyqt5-sip', exact=True) }}
        - {{ pin_subpackage('pyqt-impl', exact=True) }}
        # - {{ pin_subpackage('pyqtwebengine', exact=True) }}
        # - {{ pin_subpackage('pyqtchart', exact=True) }}

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python bindings for the Qt cross platform application toolkit'
  # The remaining entries in this section are optional, but recommended.
  description: |
    PyQt5 is a comprehensive set of Python bindings for Qt v5.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt5/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
