{% set name = "qtwebengine" %}
{% set version = "5.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #- url: https://github.com/qt/qtwebengine/archive/refs/tags/v{{ version }}-lts.tar.gz
  #  sha256: a7ed7e8755f9c781af6725ba974c27222af310fbd3ceb99251884da48799350c

  #- url: https://github.com/qt/qtwebengine-chromium/archive/refs/heads/87-based.zip
  #  sha256: dc7e37a28d9f49efe01dcef8761c1db720ffd0c98ccea9bd34a75470de056aab
  #  folder: src/3rdparty

  #- url: https://github.com/qt/qtwebengine/archive/refs/tags/v{{ version }}-lts.tar.gz
  #  sha256: a7ed7e8755f9c781af6725ba974c27222af310fbd3ceb99251884da48799350c
  #  folder: qtwebengine

  - git_url: https://code.qt.io/qt/qtwebengine.git
    git_rev: v{{ version }}-lts

  - git_url: https://code.qt.io/qt/qtwebengine-chromium.git
    git_rev: 87-based
    folder: qtwebengine-chromium
    patches:  # [aarch64 or osx]
      - 0001-aarch64-sys-state-structs.patch  # [aarch64]
      - 0002-macos-fatal-warnings.patch  # [osx]
      - 0003-macos-arm64-chromium.patch  # [osx and arm64]
      - 0004-macos-arm64-float16-conv.patch  # [osx and arm64]

  - url: https://download.qt.io/official_releases/jom/jom.zip  # [win]
    folder: jom  # [win]
    md5: f960efa8dc1e99df088d32bc1bc2157c  # [win]

  - url: https://download.qt.io/development_releases/gnuwin32/gnuwin32.zip  # [win]
    folder: gnuwin32  # [win]
    sha256: 4a9dc893cc0a1695a16102a42ef47ef2e228652891f4afea67fadd452b63656b  # [win]

build:
  number: 1

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('alsa-lib-devel') }}    # [linux]
    - {{ cdt('cups-devel') }}    # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('cups-devel') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    # - {{ cdt('pcre') }}                  # [linux and cdt_name != 'cos6']
    # - {{ cdt('libglvnd-glx') }}          # [linux and cdt_name != 'cos6']
    - pkg-config                         # [unix]
    - make                               # [unix]
    - cmake
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - perl 5.*
    - readline                           # [linux]
    - python 2.7*                        # [win]
  host:
    - gtk3
    # - libpng
    - libjpeg-turbo
    - pulseaudio                         # [linux and not aarch64]
    - gstreamer                          # [not arm64]
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - gst-plugins-base
    - gstreamer
    - libglib                            # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    - expat                              # [linux]
    - libevent                           # [linux]
    - icu
    - libpng
    - libiconv
    - nspr                               # [unix]
    - nss                                # [unix]
    - sqlite
    - mysql-devel                        # [not win]
    - postgresql                         # [not win]
    - zlib
    - libxcb                             # [linux]
    - qt >=5.15.2
    - nodejs
    - libwebp
    - openssl                            # [win]
  run:
    - gtk3
    - libpng
    - libjpeg-turbo
    - {{ pin_compatible("nodejs") }}
    - pulseaudio                         # [linux and not aarch64]
    - gstreamer                          # [not arm64]
    - qt >=5.15.2

# test:
#   # Some packages might need a `test/commands` key to check CLI.
#   # List all the packages/modules that `run_test.py` imports.
#   imports:
#     - simplejson
#     - simplejson.tests
#   # For python packages, it is useful to run pip check. However, sometimes the
#   # metadata used by pip is out of date. Thus this section is optional if it is
#   # failing.
#   requires:
#     - pip
#   commands:
#     - pip check

about:
  home: http://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
