azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
test_on_native_only: true
